### ISSUE TITLE
What happened to the original pynsmclient?

### ISSUE THREAD

**Issue by ViktorNova** [hilbrichtsoftware/pynsm2#1]
Hello! Do you still have the original pynsmclient that you wrote? 
Any particular reason you took it down? 

I wrote something using it and am having strange problems due to something I changed, and I was hoping to have a look at your original code that I started with to compare and help narrow it down. Also I like that it was simple and didn't require PyQt =) Thank you!

**Comment by hilbrichtsoftware** [comment]
PyNsm1 is gone and exists only privately.  PyNSM2 is better in any regard.

**Comment by ViktorNova** [comment]
OK thank you, I will attempt to migrate this to use PyNSM2 instead.

(also my apoogies, I just realized PyQT is only needed for your demo NSM app)

**Comment by hilbrichtsoftware** [comment]
Did you get my private e-mail message I wrote an hour after you opened this issue? I don't know how to contact you directly, I thought github took care of it.

**Comment by ViktorNova** [comment]
I did finally notice that, thank you very much! 
I decided instead to migrate to pynsm2 and am more happy with it =)
